---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure iptables is installed (debian)
  apt:
    name: iptables
  when: ansible_os_family == 'Debian'

- name: Ensure iptables is installed (redhat)
  yum:
    name: iptables
  when: ansible_os_family == 'RedHat'

- name: Ensure that config directory is exists
  file:
    state: directory
    path: "{{ iptables_confdir }}"

- name: Ensure the iptables load path exists
  file:
    state: directory
    path: /etc/network/if-up.d
  when: iptables_load_path

- name: Prepare iptables rules
  template:
    src: iptables_rules.j2
    dest: "{{ iptables_rules_path }}"
    owner: root
    group: root
    mode: 0740
  notify: iptables load

- name: Autoload the rules
  template:
    src: iptables_load.j2
    dest: "{{ iptables_load_path }}"
    owner: root
    group: root
    mode: 750
  when: iptables_load_path
